People/config/routes.rb
People::Application.routes.draw do
  #Resources RESTful (run 'rake routes' to see all routes/actions)
  resources :people
  get "people/:id" => "people#show"

  # You can have the root of your site routed with "root"
  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

People/app/models/person.rb
class Person < ActiveRecord::Base
	#the attributes are mapped in ActiveRecord automatically
	validates :name, presence: true, length: {minimum:5,maximum:50}
	validates :age, presence: true, numericality: true
end

People/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

People/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def new

  end
end

People/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :getPerson, only: [:show, :edit, :update, :destroy]

  # action to index, list all people
  def index
  	@people = Person.all
  end

  # action to new person, is called before render the view
  def new
  end

  def getPerson
    @person = Person.find(params[:id])
  end

  #action to show a specific person, is called before render the view
  def show
  	if !@person
  		flash[:message] = "Person not found"
  	end
  	render action: "edit"
  end

  #action to edit a specific person, is called before render the view
  def edit
  end

  #action to save the person on database
  def create
  	#@person = Person.new(params[:person]) #create a new person
  	@person = Person.new(post_params) #create a new person using security post
  	if @person.save #save the person in database, but the rails' feature strong_parameteres doesn't allow to save without specify the fields those are accepted
  		redirect_to @person
	else
		flash[:type] = "warning"
  		flash[:message] = "Please, complete the required fields"
		render "new"
	end
  end

  #action to update the person on database
  def update
  	if @person.update(post_params)
		flash[:type] = "success"
  		flash[:message] = "Saved successfully"
  		redirect_to @person
	else
		flash[:type] = "warning"
  		flash[:message] = "Please, complete the required fields"
		render "edit"
	end
  end

  #action to delete the person from database
  def destroy
  	if @person.destroy
		flash[:type] = "success"
  		flash[:message] = "Deleted successfully"
  		redirect_to people_path
	else
		flash[:type] = "warning"
  		flash[:message] = "Person wasn't deleted"
		render "edit"
	end
  end

  private
  	def post_params
  		#method params returns an ActiveSupport::HashWithIndifferentAccess
  		params.require(:person).permit(:name, :age)
  	end

end

People/app/helpers/application_helper.rb
module ApplicationHelper
end

People/app/helpers/home_helper.rb
module HomeHelper
end

People/app/helpers/people_helper.rb
module PeopleHelper
end

People/app/views/home/index.html.erb
<h3>Welcome to manage people</h3>
<%= link_to "New", new_person_path, :class => "btn btn-success" %>
<%= link_to "View", people_path, :class => "btn btn-default" %>

People/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>People</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "bootstrap.min", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="row"><div class="well"><h1>People database</h1></div></div>
	<div class="row">
		<% if flash[:message] %>
			<div class="alert alert-<%= flash[:type] %>"><%= flash[:message] %></div>
		<% end %>
	</div>
	<%= yield %>
</div>
</body>
</html>

People/app/views/people/edit.html.erb
<% # page to edit a person %>
<div class="panel panel-default row">
	<div class="panel-heading">Edit <%= @person.id %></div>
	<div class="panel-body">
		<%= form_for @person, class: "form-horizontal" do |f| %>
			<div class="form-group row"><div class="col-md-3">
				<%= f.label :id %>
				<%= f.text_field :id, class: "form-control", readonly: "true" %>
			</div></div>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control", placeholder: "Enter the name", maxlength: 50 %>
			</div>
			<div class="form-group">
				<%= f.label :age %>
				<%= f.text_field :age, class: "form-control", placeholder: "Enter the age" %>
			</div>
			<%= f.submit "Save", :url => people_path, :class => "btn btn-primary" %>
			<%= link_to "Delete", person_path(@person), method: :delete, :class => "btn btn-danger", data: { confirm: 'Are you sure?' } %>
			<%= link_to "Back", people_path, :class => "btn btn-default" %>
		
		<% end %>
	</div>
</div>

People/app/views/people/index.html.erb
<div class="row panel panel-default">
<div class="panel-heading">People registered</div>
<div class="panel-body">
	<table class="table table-striped">
		<thead><th>ID</th><th>Name</th><th>Age</th><th>Actions</th></thead>
		<tbody>
			<% @people.each do |p| %>
				<tr>
					<td><%= p.id %></td><td><%= p.name %></td><td><%= p.age %></td>
					<td>
						<%= link_to "Edit", edit_person_path(p.id), :class => "btn btn-success" %>
						<%= link_to "Delete", person_path(p), method: :delete, :class => "btn btn-danger", data: { confirm: 'Are you sure?' } %>
					</td>
				</tr>
			<% end %>
			<% if @people.size == 0 %>
				<tr><td colspan="4"><em>people not found</em></td></tr>
			<% end %>
		</tbody>
	</table>
</div>
<div class="panel-footer">
	<%= link_to "New", new_person_path, :class => "btn btn-default" %>
	<%= link_to "Home", "/", :class => "btn btn-default" %>
</div>
</div>

People/app/views/people/new.html.erb
<% # page to save a new person %>
<div class="panel panel-default row">
	<div class="panel-heading">New</div>
	<div class="panel-body">
		<%= form_for :person, url: people_path, class: "form-horizontal" do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control", placeholder: "Enter the name" %>
			</div>
			<div class="form-group">
				<%= f.label :age %>
				<%= f.text_field :age, class: "form-control", placeholder: "Enter the age", maxlength: 50 %>
			</div>
			<%= f.submit "Save", :class => "btn btn-primary" %>
			<%= link_to "Back", people_path, :class => "btn btn-default" %>

			<% if @person and @person.errors.any? %>
				<div class="alert alert-danger" style="margin-top:10px;">
					The person wasn't saved, fix the errors bellow:
					<ul>
					<% @person.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
					</ul>
				</div>
			<% end %>
		<% end %>
	</div>
</div>